version: "3"

services:
        db_postgres:
                image: postgres:11.5
                healthcheck:
                        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
                        timeout: 45s
                        retries: 10
                restart: 
                        always
                ports:
                        - 5432:5432
                env_file:
                        - ./.env
                volumes:
                        - postgres_data:/var/lib/postgresql/data
        django_app:
                build: .
                restart: always
                volumes:
                        - static:/code/static
                        - .:/code
                depends_on:
                        - db_postgres
        
        nginx:
                image: nginx:1.13
                restart: always
                ports:
                        - 80:80
                volumes:
                        - ./config/nginx/conf.d:/etc/nginx/conf.d
                        - static:/code/static
                depends_on:
                        - django_app


volumes:
        .:
        postgres_data:
        static:

